# Generated by Django 5.1.4 on 2024-12-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_rename_clients_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Place',
        ),
    ]
