# Generated by Django 5.1.4 on 2024-12-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_country_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место отдыха', 'verbose_name_plural': 'Места отдыха'},
        ),
    ]
